// auto-generated by foster-testgen — do not edit
// machine    : counter
// Regenerate : cargo run -p counter --bin gen_tests

import { encode, decode } from '@msgpack/msgpack';

// ── types ─────────────────────────────────────────────────────────────────────

export type CounterState = 'error' | 'idle';
export type CounterEvent = 'break_it' | 'decrement' | 'increment' | 'recover' | 'reset';

export interface CounterSnapshot {
  machine_id : 'counter';
  state      : CounterState;
  context    : Record<string, unknown>;
  version    : number;
  last_event?: CounterEvent;
}

// ── client ────────────────────────────────────────────────────────────────────

/** Typed programmatic client for the `counter` Foster machine. */
export class CounterClient {
  constructor(
    private readonly baseUrl = 'http://localhost:3000',
    private readonly session = 'default'
  ) {}

  /** Fire an event and return the resulting snapshot. */
  async sendEvent(
    event  : CounterEvent,
    payload: Record<string, unknown> = {}
  ): Promise<CounterSnapshot> {
    const body = encode({ machine: 'counter', event, payload, session: this.session });
    const res  = await fetch(`${this.baseUrl}/transition`, {
      method : 'POST',
      headers: { 'Content-Type': 'application/msgpack' },
      body,
    });
    if (!res.ok) throw new Error(`sendEvent(${event}) → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as CounterSnapshot;
  }

  /** Get the current snapshot. */
  async getState(): Promise<CounterSnapshot> {
    const res = await fetch(
      `${this.baseUrl}/state?machine=counter&session=${this.session}`,
      { headers: { Accept: 'application/msgpack' } }
    );
    if (!res.ok) throw new Error(`getState → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as CounterSnapshot;
  }

  /** Inject a snapshot (debug builds / FOSTER_TEST_MODE=1 only). */
  async setState(
    state  : CounterState,
    context: Record<string, unknown> = {},
    version = 0
  ): Promise<void> {
    const res = await fetch(
      `${this.baseUrl}/test/state?session=${this.session}`,
      {
        method : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body   : JSON.stringify({ machine_id: 'counter', state, context, version }),
      }
    );
    if (!res.ok) throw new Error(`setState(${state}) → HTTP ${res.status}`);
  }
}
