// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : counter
// states  : error, idle
// edges   : 5
//
// Regenerate: cargo run -p counter --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3000';
const MACHINE_ID = 'counter';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side, then reload so the WASM client reflects it.
/// Playwright retries the `toHaveAttribute` assertion until the WASM runtime
/// has fetched and applied the snapshot (handles the async init race).
async function injectAndReload(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  await request.post(`${BASE_URL}/test/state`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  await page.reload();
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', state);
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('counter | error →[recover]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'error', {"count":0});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->recover"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('counter | idle →[break_it]→ error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"count":0});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->break_it"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('counter | idle →[decrement]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"count":0});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->decrement"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('counter | idle →[increment]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"count":0});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->increment"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('counter | idle →[reset]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"count":0});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->reset"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('counter | inject state: error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'error', {"count":0});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('counter | inject state: idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"count":0});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

