use foster_core::Machine;
use std::fmt::Write as _;

/// Generate a TypeScript Playwright test file from a machine definition.
///
/// Each edge in the state graph gets exactly one test:
///   1. Inject the source state via `POST /test/state`
///   2. Reload the page so the client reflects the injected state
///   3. Assert `data-fx-state` matches the source state
///   4. Trigger the transition via the `[fx-on="click-><event>"]` element
///   5. Assert `data-fx-state` matches the target state
///
/// Deterministic output — no randomness — so regenerating is safe to diff.
pub fn generate(machine: &Machine, base_url: &str) -> String {
    let mut transitions = machine.transitions();
    // Sort for stable output
    transitions.sort_by_key(|&(from, event, to)| (from, event, to));

    let state_names = {
        let mut names: Vec<&str> = machine.state_names();
        names.sort();
        names
    };

    let initial_ctx = serde_json::to_string(&machine.initial_context)
        .unwrap_or_else(|_| "{}".to_string());

    let mut out = String::new();

    // ── file header ──────────────────────────────────────────────────────────
    writeln!(out, "// ─── auto-generated by foster-testgen ────────────────────────────────────────").unwrap();
    writeln!(out, "// machine : {}", machine.id).unwrap();
    writeln!(out, "// states  : {}", state_names.join(", ")).unwrap();
    writeln!(out, "// edges   : {}", transitions.len()).unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Regenerate: cargo run -p counter --bin gen_tests").unwrap();
    writeln!(out, "// Edit freely — regenerating will not overwrite this file; diff and merge.").unwrap();
    writeln!(out, "// ─────────────────────────────────────────────────────────────────────────────").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import {{ test, expect, type Page, type APIRequestContext }} from '@playwright/test';").unwrap();
    writeln!(out).unwrap();

    // ── constants ────────────────────────────────────────────────────────────
    writeln!(out, "const BASE_URL   = '{base_url}';").unwrap();
    writeln!(out, "const MACHINE_ID = '{}';", machine.id).unwrap();
    writeln!(out, "const ROOT       = `[fx-machine=\"${{MACHINE_ID}}\"]`;").unwrap();
    writeln!(out).unwrap();

    // ── helper ───────────────────────────────────────────────────────────────
    write!(out, "\
/// Inject a snapshot server-side, then reload so the WASM client reflects it.
/// Playwright retries the `toHaveAttribute` assertion until the WASM runtime
/// has fetched and applied the snapshot (handles the async init race).
async function injectAndReload(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {{
  await request.post(`${{BASE_URL}}/test/state`, {{
    data: {{ machine_id: MACHINE_ID, state, context, version }},
  }});
  await page.reload();
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', state);
}}

").unwrap();

    // ── transition tests ─────────────────────────────────────────────────────
    writeln!(out, "// ── transition coverage ─────────────────────────────────────────────────────").unwrap();
    writeln!(out, "// One test per edge.  All edge permutations are covered by construction.").unwrap();
    writeln!(out).unwrap();

    // Build a map of context values per state.  We only have initial_context
    // from the machine definition; use it for every source state as a scaffold.
    // The LLM or human can specialize per state if needed.
    let ctx_for_state = |_state: &str| -> &str { &initial_ctx };

    for (from, event, to) in &transitions {
        let ctx = ctx_for_state(from);
        write!(out, "\
test('{machine_id} | {from} →[{event}]→ {to}', async ({{ page, request }}) => {{
  await page.goto(BASE_URL);
  await injectAndReload(request, page, '{from}', {ctx});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on=\"click->{event}\"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', '{to}');
}});

",
            machine_id = machine.id,
            from = from,
            event = event,
            to = to,
            ctx = ctx,
        ).unwrap();
    }

    // ── state snapshot injection tests ───────────────────────────────────────
    writeln!(out, "// ── snapshot injection (no interaction) ──────────────────────────────────────").unwrap();
    writeln!(out, "// Verify that POST /test/state correctly sets the DOM state.").unwrap();
    writeln!(out, "// These are the building blocks; transition tests depend on them being correct.").unwrap();
    writeln!(out).unwrap();

    for state in &state_names {
        let ctx = ctx_for_state(state);
        write!(out, "\
test('{machine_id} | inject state: {state}', async ({{ page, request }}) => {{
  await page.goto(BASE_URL);
  await injectAndReload(request, page, '{state}', {ctx});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', '{state}');
}});

",
            machine_id = machine.id,
            state = state,
            ctx = ctx,
        ).unwrap();
    }

    out
}

/// Generate a minimal `playwright.config.ts` pointing at `base_url`.
pub fn generate_playwright_config(base_url: &str) -> String {
    format!(
        r#"import {{ defineConfig }} from '@playwright/test';

export default defineConfig({{
  testDir   : './tests',
  timeout   : 10_000,
  use: {{
    baseURL        : '{base_url}',
    // Keeps the browser open long enough to see what happened on failure.
    actionTimeout  : 5_000,
  }},
  // Run against a locally started server.  Adjust command/port as needed.
  webServer: {{
    command : 'cargo run -p counter',
    url     : '{base_url}',
    reuseExistingServer: !process.env.CI,
  }},
}});
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use foster_core::MachineBuilder;
    use serde_json::json;

    fn counter_machine() -> std::sync::Arc<Machine> {
        MachineBuilder::new("counter", "idle", json!({ "count": 0 }))
            .state("error")
            .on("idle", "increment", "idle", None)
            .on("idle", "break_it", "error", None)
            .on("error", "recover", "idle", None)
            .build()
    }

    #[test]
    fn output_is_deterministic() {
        let m = counter_machine();
        let a = generate(&m, "http://localhost:3000");
        let b = generate(&m, "http://localhost:3000");
        assert_eq!(a, b);
    }

    #[test]
    fn every_transition_appears() {
        let m = counter_machine();
        let out = generate(&m, "http://localhost:3000");
        assert!(out.contains("idle →[increment]→ idle"));
        assert!(out.contains("idle →[break_it]→ error"));
        assert!(out.contains("error →[recover]→ idle"));
    }

    #[test]
    fn every_state_injection_appears() {
        let m = counter_machine();
        let out = generate(&m, "http://localhost:3000");
        assert!(out.contains("inject state: idle"));
        assert!(out.contains("inject state: error"));
    }

    #[test]
    fn playwright_assertions_use_data_attribute() {
        let m = counter_machine();
        let out = generate(&m, "http://localhost:3000");
        // Every test assertion goes through data-fx-state
        assert!(out.contains("toHaveAttribute('data-fx-state'"));
    }

    #[test]
    fn config_contains_base_url() {
        let cfg = generate_playwright_config("http://localhost:3000");
        assert!(cfg.contains("http://localhost:3000"));
        assert!(cfg.contains("defineConfig"));
    }
}
