// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : notion
// states  : editing, reading
// edges   : 10
//
// Regenerate: cargo run -p notion --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3006';
const MACHINE_ID = 'notion';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  // Wait for WASM to finish its initial bootstrap (data-fx-state is stamped
  // after the first snapshot is applied, and the SSE listener is wired up
  // before that fetch — so by this point the SSE channel is live).
  await expect(root).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('notion | editing →[change_type]→ editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->change_type"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('notion | editing →[commit_edit]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->commit_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | editing →[discard_edit]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->discard_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | reading →[add_block]→ editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->add_block"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('notion | reading →[delete_block]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->delete_block"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | reading →[focus_block]→ editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->focus_block"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('notion | reading →[move_down]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->move_down"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | reading →[move_up]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->move_up"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | reading →[toggle_todo]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->toggle_todo"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

test('notion | reading →[update_title]→ reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->update_title"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

// ── multi-step walk ─────────────────────────────────────────────────────────
// A single deterministic walk visiting every state ≥2× catches ordering bugs
// (SSE snapshot rollback, stale fx-class) that single-edge tests miss.

test('notion | walk visits every state ≥2× in sequence', async ({ page }) => {
  await page.goto(BASE_URL);
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sequence = ['add_block', 'change_type', 'commit_edit'];
  const expected = ['editing', 'editing', 'reading'];
  for (let i = 0; i < sequence.length; i++) {
    await page.locator(`[fx-on="click->${sequence[i]}"]`).first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', expected[i], { timeout: 3000 });
  }
});

// ── rapid toggle pairs ──────────────────────────────────────────────────────
// Bidirectional pairs ping-ponged 4× — catches animation/fx-class sync bugs.

test('notion | rapid toggle editing↔reading stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->commit_edit"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading', { timeout: 3000 });
    await page.locator('[fx-on="click->focus_block"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing', { timeout: 3000 });
  }
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('notion | inject state: editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('notion | inject state: reading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'reading', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'reading');
});

