// auto-generated by foster-testgen — do not edit
// machine    : aura
// Regenerate : cargo run -p aura --bin gen_tests

import { encode, decode } from '@msgpack/msgpack';

// ── types ─────────────────────────────────────────────────────────────────────

export type AuraState = 'calm' | 'energized' | 'focused' | 'overwhelmed';
export type AuraEvent = 'calm' | 'energize' | 'focus' | 'overwhelm';

export interface AuraSnapshot {
  machine_id : 'aura';
  state      : AuraState;
  context    : Record<string, unknown>;
  version    : number;
  last_event?: AuraEvent;
}

// ── client ────────────────────────────────────────────────────────────────────

/** Typed programmatic client for the `aura` Foster machine. */
export class AuraClient {
  constructor(
    private readonly baseUrl = 'http://localhost:3003',
    private readonly session = 'default'
  ) {}

  /** Fire an event and return the resulting snapshot. */
  async sendEvent(
    event  : AuraEvent,
    payload: Record<string, unknown> = {}
  ): Promise<AuraSnapshot> {
    const body = encode({ machine: 'aura', event, payload, session: this.session });
    const res  = await fetch(`${this.baseUrl}/transition`, {
      method : 'POST',
      headers: { 'Content-Type': 'application/msgpack' },
      body,
    });
    if (!res.ok) throw new Error(`sendEvent(${event}) → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as AuraSnapshot;
  }

  /** Get the current snapshot. */
  async getState(): Promise<AuraSnapshot> {
    const res = await fetch(
      `${this.baseUrl}/state?machine=aura&session=${this.session}`,
      { headers: { Accept: 'application/msgpack' } }
    );
    if (!res.ok) throw new Error(`getState → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as AuraSnapshot;
  }

  /** Inject a snapshot (debug builds / FOSTER_TEST_MODE=1 only). */
  async setState(
    state  : AuraState,
    context: Record<string, unknown> = {},
    version = 0
  ): Promise<void> {
    const res = await fetch(
      `${this.baseUrl}/test/state?session=${this.session}`,
      {
        method : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body   : JSON.stringify({ machine_id: 'aura', state, context, version }),
      }
    );
    if (!res.ok) throw new Error(`setState(${state}) → HTTP ${res.status}`);
  }
}
