// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : aura
// states  : calm, energized, focused, overwhelmed
// edges   : 12
//
// Regenerate: cargo run -p counter --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3003';
const MACHINE_ID = 'aura';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('aura | calm →[energize]→ energized', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'calm', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->energize"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'energized');
});

test('aura | calm →[focus]→ focused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'calm', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->focus"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'focused');
});

test('aura | calm →[overwhelm]→ overwhelmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'calm', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->overwhelm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'overwhelmed');
});

test('aura | energized →[calm]→ calm', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'energized', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->calm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'calm');
});

test('aura | energized →[focus]→ focused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'energized', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->focus"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'focused');
});

test('aura | energized →[overwhelm]→ overwhelmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'energized', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->overwhelm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'overwhelmed');
});

test('aura | focused →[calm]→ calm', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'focused', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->calm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'calm');
});

test('aura | focused →[energize]→ energized', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'focused', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->energize"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'energized');
});

test('aura | focused →[overwhelm]→ overwhelmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'focused', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->overwhelm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'overwhelmed');
});

test('aura | overwhelmed →[calm]→ calm', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'overwhelmed', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->calm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'calm');
});

test('aura | overwhelmed →[energize]→ energized', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'overwhelmed', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->energize"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'energized');
});

test('aura | overwhelmed →[focus]→ focused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'overwhelmed', {});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->focus"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'focused');
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('aura | inject state: calm', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'calm', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'calm');
});

test('aura | inject state: energized', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'energized', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'energized');
});

test('aura | inject state: focused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'focused', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'focused');
});

test('aura | inject state: overwhelmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'overwhelmed', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'overwhelmed');
});

