// auto-generated by foster-testgen — do not edit
// machine    : player
// Regenerate : cargo run -p player --bin gen_tests

import { encode, decode } from '@msgpack/msgpack';

// ── types ─────────────────────────────────────────────────────────────────────

export type PlayerState = 'ended' | 'error' | 'idle' | 'loading' | 'paused' | 'playing';
export type PlayerEvent = 'back_10' | 'dismiss' | 'end' | 'fail' | 'forward_10' | 'load' | 'pause' | 'play' | 'ready' | 'replay' | 'retry';

export interface PlayerSnapshot {
  machine_id : 'player';
  state      : PlayerState;
  context    : Record<string, unknown>;
  version    : number;
  last_event?: PlayerEvent;
}

// ── client ────────────────────────────────────────────────────────────────────

/** Typed programmatic client for the `player` Foster machine. */
export class PlayerClient {
  constructor(
    private readonly baseUrl = 'http://localhost:3001',
    private readonly session = 'default'
  ) {}

  /** Fire an event and return the resulting snapshot. */
  async sendEvent(
    event  : PlayerEvent,
    payload: Record<string, unknown> = {}
  ): Promise<PlayerSnapshot> {
    const body = encode({ machine: 'player', event, payload, session: this.session });
    const res  = await fetch(`${this.baseUrl}/transition`, {
      method : 'POST',
      headers: { 'Content-Type': 'application/msgpack' },
      body,
    });
    if (!res.ok) throw new Error(`sendEvent(${event}) → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as PlayerSnapshot;
  }

  /** Get the current snapshot. */
  async getState(): Promise<PlayerSnapshot> {
    const res = await fetch(
      `${this.baseUrl}/state?machine=player&session=${this.session}`,
      { headers: { Accept: 'application/msgpack' } }
    );
    if (!res.ok) throw new Error(`getState → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as PlayerSnapshot;
  }

  /** Inject a snapshot (debug builds / FOSTER_TEST_MODE=1 only). */
  async setState(
    state  : PlayerState,
    context: Record<string, unknown> = {},
    version = 0
  ): Promise<void> {
    const res = await fetch(
      `${this.baseUrl}/test/state?session=${this.session}`,
      {
        method : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body   : JSON.stringify({ machine_id: 'player', state, context, version }),
      }
    );
    if (!res.ok) throw new Error(`setState(${state}) → HTTP ${res.status}`);
  }
}
