// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : player
// states  : ended, error, idle, loading, paused, playing
// edges   : 14
//
// Regenerate: cargo run -p counter --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3001';
const MACHINE_ID = 'player';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side, then reload so the WASM client reflects it.
/// Playwright retries the `toHaveAttribute` assertion until the WASM runtime
/// has fetched and applied the snapshot (handles the async init race).
async function injectAndReload(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  await request.post(`${BASE_URL}/test/state`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  await page.reload();
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', state);
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('player | ended →[load]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->load"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | ended →[replay]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->replay"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | error →[dismiss]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->dismiss"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('player | error →[retry]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->retry"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | idle →[load]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->load"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | loading →[fail]→ error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->fail"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('player | loading →[ready]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->ready"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | paused →[back_10]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | paused →[forward_10]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->forward_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | paused →[play]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->play"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[back_10]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[end]→ ended', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->end"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'ended');
});

test('player | playing →[forward_10]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->forward_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[pause]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->pause"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('player | inject state: ended', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'ended');
});

test('player | inject state: error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('player | inject state: idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'idle', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('player | inject state: loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | inject state: paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | inject state: playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectAndReload(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

