// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : player
// states  : ended, error, idle, loading, paused, playing
// edges   : 14
//
// Regenerate: cargo run -p player --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3001';
const MACHINE_ID = 'player';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  // Wait for WASM to finish its initial bootstrap (data-fx-state is stamped
  // after the first snapshot is applied, and the SSE listener is wired up
  // before that fetch — so by this point the SSE channel is live).
  await expect(root).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('player | ended →[load]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->load"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | ended →[replay]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->replay"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | error →[dismiss]→ idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->dismiss"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('player | error →[retry]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->retry"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | idle →[load]→ loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'idle', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->load"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | loading →[fail]→ error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->fail"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('player | loading →[ready]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->ready"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | paused →[back_10]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | paused →[forward_10]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->forward_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | paused →[play]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->play"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[back_10]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[end]→ ended', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->end"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'ended');
});

test('player | playing →[forward_10]→ playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->forward_10"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

test('player | playing →[pause]→ paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->pause"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

// ── multi-step walk ─────────────────────────────────────────────────────────
// A single deterministic walk visiting every state ≥2× catches ordering bugs
// (SSE snapshot rollback, stale fx-class) that single-edge tests miss.

test('player | walk visits every state ≥2× in sequence', async ({ page }) => {
  await page.goto(BASE_URL);
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sequence = ['load', 'fail', 'dismiss', 'load', 'ready', 'end', 'replay', 'pause', 'back_10', 'back_10', 'play', 'end', 'load', 'fail'];
  const expected = ['loading', 'error', 'idle', 'loading', 'playing', 'ended', 'playing', 'paused', 'paused', 'paused', 'playing', 'ended', 'loading', 'error'];
  for (let i = 0; i < sequence.length; i++) {
    await page.locator(`[fx-on="click->${sequence[i]}"]`).first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', expected[i], { timeout: 3000 });
  }
});

// ── rapid toggle pairs ──────────────────────────────────────────────────────
// Bidirectional pairs ping-ponged 4× — catches animation/fx-class sync bugs.

test('player | rapid toggle ended↔playing stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->replay"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing', { timeout: 3000 });
    await page.locator('[fx-on="click->end"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'ended', { timeout: 3000 });
  }
});

test('player | rapid toggle error↔loading stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->retry"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading', { timeout: 3000 });
    await page.locator('[fx-on="click->fail"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error', { timeout: 3000 });
  }
});

test('player | rapid toggle paused↔playing stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->play"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing', { timeout: 3000 });
    await page.locator('[fx-on="click->pause"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused', { timeout: 3000 });
  }
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('player | inject state: ended', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'ended', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'ended');
});

test('player | inject state: error', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'error', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'error');
});

test('player | inject state: idle', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'idle', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'idle');
});

test('player | inject state: loading', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'loading', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'loading');
});

test('player | inject state: paused', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'paused', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'paused');
});

test('player | inject state: playing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'playing', {"artist":"","duration":0,"error":"","position":0,"title":""});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'playing');
});

