// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : checkout
// states  : cart, confirmed, failed, payment, processing, review, shipping
// edges   : 11
//
// Regenerate: cargo run -p checkout --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3004';
const MACHINE_ID = 'checkout';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  // Wait for WASM to finish its initial bootstrap (data-fx-state is stamped
  // after the first snapshot is applied, and the SSE listener is wired up
  // before that fetch — so by this point the SSE channel is live).
  await expect(root).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('checkout | cart →[start_checkout]→ shipping', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'cart', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_checkout"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'shipping');
});

test('checkout | confirmed →[new_order]→ cart', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirmed', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->new_order"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'cart');
});

test('checkout | failed →[retry]→ payment', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'failed', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->retry"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment');
});

test('checkout | payment →[back]→ shipping', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'payment', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'shipping');
});

test('checkout | payment →[save_payment]→ review', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'payment', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save_payment"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'review');
});

test('checkout | processing →[fail]→ failed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'processing', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->fail"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'failed');
});

test('checkout | processing →[succeed]→ confirmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'processing', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->succeed"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirmed');
});

test('checkout | review →[back]→ payment', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'review', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment');
});

test('checkout | review →[place_order]→ processing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'review', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->place_order"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'processing');
});

test('checkout | shipping →[back]→ cart', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'shipping', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'cart');
});

test('checkout | shipping →[save_shipping]→ payment', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'shipping', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save_shipping"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment');
});

// ── multi-step walk ─────────────────────────────────────────────────────────
// A single deterministic walk visiting every state ≥2× catches ordering bugs
// (SSE snapshot rollback, stale fx-class) that single-edge tests miss.

test('checkout | walk visits every state ≥2× in sequence', async ({ page }) => {
  await page.goto(BASE_URL);
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sequence = ['start_checkout', 'save_shipping', 'save_payment', 'place_order', 'fail', 'retry', 'back', 'back', 'start_checkout', 'back', 'start_checkout', 'save_shipping', 'save_payment', 'place_order', 'succeed', 'new_order', 'start_checkout', 'save_shipping', 'save_payment', 'place_order', 'fail', 'retry', 'save_payment', 'place_order', 'succeed'];
  const expected = ['shipping', 'payment', 'review', 'processing', 'failed', 'payment', 'shipping', 'cart', 'shipping', 'cart', 'shipping', 'payment', 'review', 'processing', 'confirmed', 'cart', 'shipping', 'payment', 'review', 'processing', 'failed', 'payment', 'review', 'processing', 'confirmed'];
  for (let i = 0; i < sequence.length; i++) {
    await page.locator(`[fx-on="click->${sequence[i]}"]`).first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', expected[i], { timeout: 3000 });
  }
});

// ── rapid toggle pairs ──────────────────────────────────────────────────────
// Bidirectional pairs ping-ponged 4× — catches animation/fx-class sync bugs.

test('checkout | rapid toggle cart↔shipping stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'cart', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->start_checkout"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'shipping', { timeout: 3000 });
    await page.locator('[fx-on="click->back"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'cart', { timeout: 3000 });
  }
});

test('checkout | rapid toggle payment↔shipping stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'payment', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->back"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'shipping', { timeout: 3000 });
    await page.locator('[fx-on="click->save_shipping"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment', { timeout: 3000 });
  }
});

test('checkout | rapid toggle payment↔review stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'payment', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->save_payment"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'review', { timeout: 3000 });
    await page.locator('[fx-on="click->back"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment', { timeout: 3000 });
  }
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('checkout | inject state: cart', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'cart', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'cart');
});

test('checkout | inject state: confirmed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirmed', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirmed');
});

test('checkout | inject state: failed', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'failed', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'failed');
});

test('checkout | inject state: payment', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'payment', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'payment');
});

test('checkout | inject state: processing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'processing', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'processing');
});

test('checkout | inject state: review', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'review', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'review');
});

test('checkout | inject state: shipping', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'shipping', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'shipping');
});

