// auto-generated by foster-testgen — do not edit
// machine    : checkout
// Regenerate : cargo run -p checkout --bin gen_tests

import { encode, decode } from '@msgpack/msgpack';

// ── types ─────────────────────────────────────────────────────────────────────

export type CheckoutState = 'cart' | 'confirmed' | 'failed' | 'payment' | 'processing' | 'review' | 'shipping';
export type CheckoutEvent = 'back' | 'fail' | 'new_order' | 'place_order' | 'retry' | 'save_payment' | 'save_shipping' | 'start_checkout' | 'succeed';

export interface CheckoutSnapshot {
  machine_id : 'checkout';
  state      : CheckoutState;
  context    : Record<string, unknown>;
  version    : number;
  last_event?: CheckoutEvent;
}

// ── client ────────────────────────────────────────────────────────────────────

/** Typed programmatic client for the `checkout` Foster machine. */
export class CheckoutClient {
  constructor(
    private readonly baseUrl = 'http://localhost:3004',
    private readonly session = 'default'
  ) {}

  /** Fire an event and return the resulting snapshot. */
  async sendEvent(
    event  : CheckoutEvent,
    payload: Record<string, unknown> = {}
  ): Promise<CheckoutSnapshot> {
    const body = encode({ machine: 'checkout', event, payload, session: this.session });
    const res  = await fetch(`${this.baseUrl}/transition`, {
      method : 'POST',
      headers: { 'Content-Type': 'application/msgpack' },
      body,
    });
    if (!res.ok) throw new Error(`sendEvent(${event}) → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as CheckoutSnapshot;
  }

  /** Get the current snapshot. */
  async getState(): Promise<CheckoutSnapshot> {
    const res = await fetch(
      `${this.baseUrl}/state?machine=checkout&session=${this.session}`,
      { headers: { Accept: 'application/msgpack' } }
    );
    if (!res.ok) throw new Error(`getState → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as CheckoutSnapshot;
  }

  /** Inject a snapshot (debug builds / FOSTER_TEST_MODE=1 only). */
  async setState(
    state  : CheckoutState,
    context: Record<string, unknown> = {},
    version = 0
  ): Promise<void> {
    const res = await fetch(
      `${this.baseUrl}/test/state?session=${this.session}`,
      {
        method : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body   : JSON.stringify({ machine_id: 'checkout', state, context, version }),
      }
    );
    if (!res.ok) throw new Error(`setState(${state}) → HTTP ${res.status}`);
  }
}
