// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : plane
// states  : create, detail, edit, filter, list
// edges   : 15
//
// Regenerate: cargo run -p plane --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3005';
const MACHINE_ID = 'plane';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  // Wait for WASM to finish its initial bootstrap (data-fx-state is stamped
  // after the first snapshot is applied, and the SSE listener is wired up
  // before that fetch — so by this point the SSE channel is live).
  await expect(root).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('plane | create →[cancel_create]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'create', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel_create"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | create →[save_create]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'create', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save_create"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | detail →[add_comment]→ detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->add_comment"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | detail →[back]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->back"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | detail →[delete_issue]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->delete_issue"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | detail →[start_edit]→ edit', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'edit');
});

test('plane | edit →[cancel_edit]→ detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'edit', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | edit →[save_edit]→ detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'edit', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | filter →[apply_filter]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->apply_filter"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | filter →[clear_filter]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->clear_filter"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | filter →[close_filter]→ list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->close_filter"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

test('plane | filter →[open_issue]→ detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->open_issue"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | list →[open_create]→ create', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'list', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->open_create"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'create');
});

test('plane | list →[open_issue]→ detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'list', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->open_issue"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | list →[toggle_filter]→ filter', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'list', {});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->toggle_filter"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'filter');
});

// ── multi-step walk ─────────────────────────────────────────────────────────
// A single deterministic walk visiting every state ≥2× catches ordering bugs
// (SSE snapshot rollback, stale fx-class) that single-edge tests miss.

test('plane | walk visits every state ≥2× in sequence', async ({ page }) => {
  await page.goto(BASE_URL);
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sequence = ['open_create', 'cancel_create', 'open_issue', 'start_edit', 'cancel_edit', 'start_edit', 'cancel_edit', 'back', 'toggle_filter', 'apply_filter', 'open_create', 'cancel_create', 'toggle_filter'];
  const expected = ['create', 'list', 'detail', 'edit', 'detail', 'edit', 'detail', 'list', 'filter', 'list', 'create', 'list', 'filter'];
  for (let i = 0; i < sequence.length; i++) {
    await page.locator(`[fx-on="click->${sequence[i]}"]`).first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', expected[i], { timeout: 3000 });
  }
});

// ── rapid toggle pairs ──────────────────────────────────────────────────────
// Bidirectional pairs ping-ponged 4× — catches animation/fx-class sync bugs.

test('plane | rapid toggle create↔list stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'create', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->cancel_create"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list', { timeout: 3000 });
    await page.locator('[fx-on="click->open_create"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'create', { timeout: 3000 });
  }
});

test('plane | rapid toggle detail↔list stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->back"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list', { timeout: 3000 });
    await page.locator('[fx-on="click->open_issue"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail', { timeout: 3000 });
  }
});

test('plane | rapid toggle detail↔edit stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->start_edit"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'edit', { timeout: 3000 });
    await page.locator('[fx-on="click->save_edit"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail', { timeout: 3000 });
  }
});

test('plane | rapid toggle filter↔list stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->apply_filter"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list', { timeout: 3000 });
    await page.locator('[fx-on="click->toggle_filter"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'filter', { timeout: 3000 });
  }
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('plane | inject state: create', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'create', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'create');
});

test('plane | inject state: detail', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'detail', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'detail');
});

test('plane | inject state: edit', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'edit', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'edit');
});

test('plane | inject state: filter', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'filter', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'filter');
});

test('plane | inject state: list', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'list', {});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'list');
});

