// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : kanban
// states  : confirming_delete, creating, editing, viewing
// edges   : 10
//
// Regenerate: cargo run -p counter --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3002';
const MACHINE_ID = 'kanban';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('kanban | confirming_delete →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | confirming_delete →[confirm]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->confirm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | creating →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | creating →[save]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | editing →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | editing →[save]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | viewing →[move_task]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->move_task"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | viewing →[start_create]→ creating', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_create"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'creating');
});

test('kanban | viewing →[start_delete]→ confirming_delete', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_delete"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirming_delete');
});

test('kanban | viewing →[start_edit]→ editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});

  // Trigger the transition.
  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('kanban | inject state: confirming_delete', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirming_delete');
});

test('kanban | inject state: creating', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'creating');
});

test('kanban | inject state: editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('kanban | inject state: viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[{"column":"done","id":"1","title":"Design state model"},{"column":"in_progress","id":"2","title":"Build WASM client"},{"column":"todo","id":"3","title":"Write tests"}]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

