// ─── auto-generated by foster-testgen ────────────────────────────────────────
// machine : kanban
// states  : confirming_delete, creating, editing, viewing
// edges   : 10
//
// Regenerate: cargo run -p kanban --bin gen_tests
// Edit freely — regenerating will not overwrite this file; diff and merge.
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect, type Page, type APIRequestContext } from '@playwright/test';

const BASE_URL   = 'http://localhost:3002';
const MACHINE_ID = 'kanban';
const ROOT       = `[fx-machine="${MACHINE_ID}"]`;

/// Inject a snapshot server-side.
/// The WASM client subscribes to SSE — the server pushes the new snapshot
/// immediately, so `page.reload()` is not needed.  The assertion waits up to
/// 3 s for the SSE push to arrive and be applied to the DOM.
///
/// `data-fx-session` on the machine root carries the session ID that was
/// assigned when the page loaded, so each test tab gets its own isolated state.
async function injectState(
  request : APIRequestContext,
  page    : Page,
  state   : string,
  context : Record<string, unknown>,
  version = 0
): Promise<void> {
  const root = page.locator(ROOT);
  // Wait for WASM to finish its initial bootstrap (data-fx-state is stamped
  // after the first snapshot is applied, and the SSE listener is wired up
  // before that fetch — so by this point the SSE channel is live).
  await expect(root).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sid  = (await root.getAttribute('data-fx-session')) ?? 'default';
  await request.post(`${BASE_URL}/test/state?session=${sid}`, {
    data: { machine_id: MACHINE_ID, state, context, version },
  });
  // SSE delivers the snapshot without a reload.
  await expect(root).toHaveAttribute('data-fx-state', state, { timeout: 3000 });
}

// ── transition coverage ─────────────────────────────────────────────────────
// One test per edge.  All edge permutations are covered by construction.

test('kanban | confirming_delete →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | confirming_delete →[confirm]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->confirm"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | creating →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | creating →[save]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | editing →[cancel]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->cancel"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | editing →[save]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->save"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | viewing →[move_task]→ viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->move_task"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

test('kanban | viewing →[start_create]→ creating', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_create"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'creating');
});

test('kanban | viewing →[start_delete]→ confirming_delete', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_delete"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirming_delete');
});

test('kanban | viewing →[start_edit]→ editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});

  // The `[fx-on]` attribute doubles as a universal locator — no test IDs needed.
  await page.locator('[fx-on="click->start_edit"]').first().click();

  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

// ── multi-step walk ─────────────────────────────────────────────────────────
// A single deterministic walk visiting every state ≥2× catches ordering bugs
// (SSE snapshot rollback, stale fx-class) that single-edge tests miss.

test('kanban | walk visits every state ≥2× in sequence', async ({ page }) => {
  await page.goto(BASE_URL);
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', /.+/, { timeout: 5000 });
  const sequence = ['start_create', 'cancel', 'start_delete', 'cancel', 'start_edit', 'cancel', 'start_create', 'cancel', 'start_delete', 'cancel', 'start_edit'];
  const expected = ['creating', 'viewing', 'confirming_delete', 'viewing', 'editing', 'viewing', 'creating', 'viewing', 'confirming_delete', 'viewing', 'editing'];
  for (let i = 0; i < sequence.length; i++) {
    await page.locator(`[fx-on="click->${sequence[i]}"]`).first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', expected[i], { timeout: 3000 });
  }
});

// ── rapid toggle pairs ──────────────────────────────────────────────────────
// Bidirectional pairs ping-ponged 4× — catches animation/fx-class sync bugs.

test('kanban | rapid toggle confirming_delete↔viewing stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->cancel"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing', { timeout: 3000 });
    await page.locator('[fx-on="click->start_delete"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirming_delete', { timeout: 3000 });
  }
});

test('kanban | rapid toggle creating↔viewing stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->cancel"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing', { timeout: 3000 });
    await page.locator('[fx-on="click->start_create"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'creating', { timeout: 3000 });
  }
});

test('kanban | rapid toggle editing↔viewing stays in sync', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  for (let i = 0; i < 4; i++) {
    await page.locator('[fx-on="click->cancel"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing', { timeout: 3000 });
    await page.locator('[fx-on="click->start_edit"]').first().click();
    await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing', { timeout: 3000 });
  }
});

// ── snapshot injection (no interaction) ──────────────────────────────────────
// Verify that POST /test/state correctly sets the DOM state.
// These are the building blocks; transition tests depend on them being correct.

test('kanban | inject state: confirming_delete', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'confirming_delete', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'confirming_delete');
});

test('kanban | inject state: creating', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'creating', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'creating');
});

test('kanban | inject state: editing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'editing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'editing');
});

test('kanban | inject state: viewing', async ({ page, request }) => {
  await page.goto(BASE_URL);
  await injectState(request, page, 'viewing', {"confirm_id":"","draft_title":"","editing_id":"","tasks":[]});
  await expect(page.locator(ROOT)).toHaveAttribute('data-fx-state', 'viewing');
});

