// auto-generated by foster-testgen — do not edit
// machine    : kanban
// Regenerate : cargo run -p kanban --bin gen_tests

import { encode, decode } from '@msgpack/msgpack';

// ── types ─────────────────────────────────────────────────────────────────────

export type KanbanState = 'confirming_delete' | 'creating' | 'editing' | 'viewing';
export type KanbanEvent = 'cancel' | 'confirm' | 'move_task' | 'save' | 'start_create' | 'start_delete' | 'start_edit';

export interface KanbanSnapshot {
  machine_id : 'kanban';
  state      : KanbanState;
  context    : Record<string, unknown>;
  version    : number;
  last_event?: KanbanEvent;
}

// ── client ────────────────────────────────────────────────────────────────────

/** Typed programmatic client for the `kanban` Foster machine. */
export class KanbanClient {
  constructor(
    private readonly baseUrl = 'http://localhost:3002',
    private readonly session = 'default'
  ) {}

  /** Fire an event and return the resulting snapshot. */
  async sendEvent(
    event  : KanbanEvent,
    payload: Record<string, unknown> = {}
  ): Promise<KanbanSnapshot> {
    const body = encode({ machine: 'kanban', event, payload, session: this.session });
    const res  = await fetch(`${this.baseUrl}/transition`, {
      method : 'POST',
      headers: { 'Content-Type': 'application/msgpack' },
      body,
    });
    if (!res.ok) throw new Error(`sendEvent(${event}) → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as KanbanSnapshot;
  }

  /** Get the current snapshot. */
  async getState(): Promise<KanbanSnapshot> {
    const res = await fetch(
      `${this.baseUrl}/state?machine=kanban&session=${this.session}`,
      { headers: { Accept: 'application/msgpack' } }
    );
    if (!res.ok) throw new Error(`getState → HTTP ${res.status}`);
    return decode(new Uint8Array(await res.arrayBuffer())) as KanbanSnapshot;
  }

  /** Inject a snapshot (debug builds / FOSTER_TEST_MODE=1 only). */
  async setState(
    state  : KanbanState,
    context: Record<string, unknown> = {},
    version = 0
  ): Promise<void> {
    const res = await fetch(
      `${this.baseUrl}/test/state?session=${this.session}`,
      {
        method : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body   : JSON.stringify({ machine_id: 'kanban', state, context, version }),
      }
    );
    if (!res.ok) throw new Error(`setState(${state}) → HTTP ${res.status}`);
  }
}
